[phases.setup]
nixPkgs = ['python310', 'gcc', 'ffmpeg', 'opencv4']

[phases.install]
cmds = ["python -m venv /opt/venv && . /opt/venv/bin/activate && pip install -r requirements.txt"]

[start]
cmd = "python railway_start.py" 