[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "python railway_deployment.py"
healthcheckPath = "/healthz"
healthcheckTimeout = 600
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5

[nixpacks]
platforms = ["ubuntu:22.04"]

[nixpacks.setup]
nixPkgs = ["ffmpeg", "opencv", "python310", "mesa", "libGL", "gtk3", "glib", "tesseract", "cairo", "pango"] 